const pets = [
    { nome: "Dragão Sombrio Shadow", categoria: "Lendario", valor: 839.99 },
    { nome: "Dragão Morcego Bat Dragon", categoria: "Lendario", valor: 1099.99 },
    { nome: "Girafa", categoria: "Lendario", valor: 599.99 },
    { nome: "Dragão de Gelo Frost Dragon", categoria: "Lendario", valor: 439.99 },
    { nome: "Canhão de Doces", categoria: "Lendario", valor: 418.99 },
    { nome: "Coruja", categoria: "Lendario", valor: 329.99 },
    { nome: "Papagaio", categoria: "Lendario", valor: 299.99 },
    { nome: "Unicórnio Maligno Evil", categoria: "Lendario", valor: 162.99 },
    { nome: "Corvo", categoria: "Lendario", valor: 189.99 },
    { nome: "Leão em Chamas", categoria: "Lendario", valor: 89.99 },
    { nome: "Rena Ártica", categoria: "Lendario", valor: 79.90 },
    { nome: "Rei Macaco", categoria: "Lendario", valor: 29.90 },
    { nome: "Dálmata", categoria: "Ultra-Raro", valor: 89.90 },
    { nome: "Tartaruga FR", categoria: "Lendario", valor: 44.99 },
    { nome: "Tartaruga R", categoria: "Lendario", valor: 44.99 },
    { nome: "Macaco Albino", categoria: "Lendario", valor: 27.99 },
    { nome: "Macaco Albino NFR", categoria: "Lendario", valor: 79.99 },
    { nome: "Vaca", categoria: "Raro", valor: 44.99 },
    { nome: "Pônei Majestoso MFR", categoria: "Raro", valor: 69.99 },
    { nome: "Ovo de Natal", categoria: "Lendario", valor: 24.99 },
    { nome: "Flamingo", categoria: "Ultra-Raro", valor: 34.89 },
    { nome: "Pinguim Doce", categoria: "Lendario", valor: 21.99 },
    { nome: "Dragão Lavanda", categoria: "Raro", valor: 1.99 },
    { nome: "Elefante NP", categoria: "Raro", valor: 29.99 },
    { nome: "Golfinho Roxo / Dolphin NP", categoria: "Raro", valor: 0.50 },
    { nome: "Leão", categoria: "Ultra-Raro", valor: 21.50 },
    { nome: "Kitsune NFR", categoria: "Lendario", valor: 7.50 },
    { nome: "Cachorro Azul", categoria: "Incomum", valor: 23.50 },
    { nome: "Pelicano", categoria: "Ultra-Raro", valor: 49.50 },
    { nome: "Canguru", categoria: "Lendario", valor: 33.00 },
    { nome: "Unicórnio MFR", categoria: "Lendario", valor: 89.50 },
    { nome: "Solplanante NR", categoria: "Lendario", valor: 7.50 },
    { nome: "Canguru MFR", categoria: "Lendario", valor: 199.50 },
    { nome: "Elefante FR", categoria: "Raro", valor: 29.99 },
    { nome: "Elefante R", categoria: "Raro", valor: 29.99 },
    { nome: "Elefante NP", categoria: "Raro", valor: 29.99 },
    { nome: "Crocodilo", categoria: "Ultra-Raro", valor: 22.50 },
    { nome: "Unicórnio de Balão", categoria: "Lendario", valor: 99.50 },
    { nome: "Unicórnio de Balão NFR", categoria: "Lendario", valor: 367.50 },
    { nome: "Dragão Morcego Fada", categoria: "Lendario", valor: 21.50 },
    { nome: "Leitão / Mini Pig", categoria: "Ultra-Raro", valor: 33.50 },
    { nome: "Dragão Sinistro", categoria: "Lendario", valor: 7.50 },
    { nome: "Dragão de Chocolate", categoria: "Lendario", valor: 34.50 },
    { nome: "Mashapup", categoria: "Lendario", valor: 10.50 },
    { nome: "Dragão Cupido", categoria: "Lendario", valor: 13.50 },
    { nome: "Gato Rosa", categoria: "Incomum", valor: 9.50 },
    { nome: "Dragão de Lava", categoria: "Lendario", valor: 8.00 },
    { nome: "Dragão Fantasma", categoria: "Lendario", valor: 8.50 },
    { nome: "Morcego de Morango", categoria: "Lendario", valor: 42.79 },
    { nome: "Morcego de Chocolate", categoria: "Lendario", valor: 42.79 },
    { nome: "Dragão Vermelho", categoria: "Lendario", valor: 0.90 },
    { nome: "Morcego de Fada", categoria: "Lendario", valor: 19.50 },
    { nome: "Capricórnio", categoria: "Lendario", valor: 3.50 },
    { nome: "Planador de Açúcar / Sugar FR", categoria: "Lendario", valor: 24.00 },
    { nome: "Ornitorrinco", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Rinoceronte", categoria: "Lendario", valor: 0.99 },
    { nome: "Ovo de Diamante", categoria: "Lendario", valor: 0.99 },
    { nome: "Lobo de Gelo", categoria: "Lendario", valor: 0.99 },
    { nome: "Lara Nessie", categoria: "Lendario", valor: 11.00 },
    { nome: "Frost Furry", categoria: "Lendario", valor: 11.50 },
    { nome: "Camaleão", categoria: "Lendario", valor: 0.99 },
    { nome: "Dragão Lavanda NR", categoria: "Lendario", valor: 0.99 },
    { nome: "Dragão Diamante", categoria: "Lendario", valor: 1.60 },
    { nome: "Tubarão", categoria: "Lendario", valor: 3.00 },
    { nome: "Grifo Diamante", categoria: "Lendario", valor: 1.40 },
    { nome: "Abelha Rainha", categoria: "Lendario", valor: 3.80 },
    { nome: "Nova Cobra Dourada", categoria: "Lendario", valor: 0.99 },
    { nome: "Coruja da Neve", categoria: "Lendario", valor: 1.50 },
    { nome: "Lobo de Lava", categoria: "Lendario", valor: 1.50 },
    { nome: "Fênix", categoria: "Lendario", valor: 3.50 },
    { nome: "Rena", categoria: "Lendario", valor: 0.99 },
    { nome: "Quimera", categoria: "Lendario", valor: 1.30 },
    { nome: "Canguru NFR", categoria: "Lendario", valor: 69.99 },
    { nome: "Vaga-lume", categoria: "Lendario", valor: 2.30 },
    { nome: "Capivara", categoria: "Incomum", valor: 2.50 },
    { nome: "Morsa Dourada", categoria: "Lendario", valor: 3.30 },
    { nome: "Urso de Natal", categoria: "Lendario", valor: 0.50 },
    { nome: "Skelerex", categoria: "Lendario", valor: 3.50 },
    { nome: "Dragão Antigo", categoria: "Lendario", valor: 1.30 },
    { nome: "Faisão Peito Verde", categoria: "Lendario", valor: 0.50 },
    { nome: "Joaninha Diamante", categoria: "Lendario", valor: 5.00 },
    { nome: "Falcão", categoria: "Lendario", valor: 1.40 },
    { nome: "Abelha Rei", categoria: "Lendario", valor: 1.50 },
    { nome: "Gorila Astronauta", categoria: "Lendario", valor: 3.50 },
    { nome: "Coruja da Neve", categoria: "Lendario", valor: 0.99 },
    { nome: "Rena", categoria: "Raro", valor: 2.50 },
    { nome: "Lobo de Lava", categoria: "Lendario", valor: 0.99 },
    { nome: "Cavalo de Justa", categoria: "Lendario", valor: 2.00 },
    { nome: "Polvo", categoria: "Lendario", valor: 1.80 },
    { nome: "Fênix", categoria: "Lendario", valor: 0.99 },
    { nome: "Borboleta Verde", categoria: "Lendario", valor: 4.00 },
    { nome: "Gárgula", categoria: "Lendario", valor: 1.60 },
    { nome: "Peru", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Quimera", categoria: "Lendario", valor: 0.99 },
    { nome: "Beija-flor", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Cisne", categoria: "Raro", valor: 2.50 },
    { nome: "Pato Bobo", categoria: "Incomum", valor: 2.50 },
    { nome: "Pintinho Maligno", categoria: "Lendario", valor: 0.99 },
    { nome: "Nautilus", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Hamster Dourado", categoria: "Lendario", valor: 3.00 },
    { nome: "Dragão Naga", categoria: "Lendario", valor: 1.70 },
    { nome: "Urso Polar", categoria: "Raro", valor: 0.99 },
    { nome: "Camundongo de Campo", categoria: "Lendario", valor: 50.00 },
    { nome: "Kraken", categoria: "Lendario", valor: 0.99 },
    { nome: "Cervo Dourado", categoria: "Lendario", valor: 0.99 },
    { nome: "Espinossauro", categoria: "Lendario", valor: 1.70 },
    { nome: "Amigo Cogumelo", categoria: "Lendario", valor: 1.40 },
    { nome: "Amigo Cacto", categoria: "Lendario", valor: 1.60 },
    { nome: "Criosphinx", categoria: "Lendario", valor: 1.50 },
    { nome: "Vaga-lume", categoria: "Lendario", valor: 0.99 },
    { nome: "Pinguim Rei Dourado", categoria: "Lendario", valor: 0.99 },
    { nome: "Spaniel do Palácio Real", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Pinguim Dourado", categoria: "Lendario", valor: 3.80 },
    { nome: "Unicórnio", categoria: "Lendario", valor: 8.00 },
    { nome: "Capivara", categoria: "Incomum", valor: 0.99 },
    { nome: "Mecha Meow", categoria: "Lendario", valor: 0.99 },
    { nome: "Albatroz Dourado", categoria: "Lendario", valor: 1.50 },
    { nome: "Alicorne", categoria: "Lendario", valor: 1.40 },
    { nome: "Morsa Dourada", categoria: "Lendario", valor: 0.99 },
    { nome: "Urso de Natal", categoria: "Lendario", valor: 0.99 },
    { nome: "Dragão Antigo", categoria: "Lendario", valor: 0.99 },
    { nome: "Faisão de Peito Verde", categoria: "Lendario", valor: 0.99 },
    { nome: "Joaninha Diamante", categoria: "Lendario", valor: 0.99 },
    { nome: "Falcão", categoria: "Lendario", valor: 0.99 },
    { nome: "Abelha Rei", categoria: "Lendario", valor: 0.99 },
    { nome: "Poção Montável", categoria: "Lendario", valor: 0.99 },
    { nome: "Poção Voável", categoria: "Lendario", valor: 0.99 },
    { nome: "Pato", categoria: "Incomum", valor: 0.99 },
    { nome: "Frango", categoria: "Comum", valor: 0.99 },
    { nome: "Gárgula NFR", categoria: "Lendario", valor: 0.99 },
    { nome: "Cordeiro", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Mahi Mahi Diamante", categoria: "Lendario", valor: 1.00 },
    { nome: "Dólar de Areia Vermelho", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Yeti", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Unicórnio Dourado", categoria: "Lendario", valor: 1.50 },
    { nome: "Cachorro de Milho", categoria: "Lendario", valor: 3.00 },
    { nome: "Cervo do Mal", categoria: "Lendario", valor: 1.20 },
    { nome: "Coelho Fantasma", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo Fóssil", categoria: "Lendario", valor: 0.99 },
    { nome: "Fleur de Gelo", categoria: "Lendario", valor: 1.30 },
    { nome: "Pet Bola de Neve", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Rinoceronte La", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Pinguim", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Filhote de Tubarão", categoria: "Lendario", valor: 12.00 },
    { nome: "Ovo Desértico Real", categoria: "Lendario", valor: 0.99 },
    { nome: "Cavalo Sem Cabeça", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Baku", categoria: "Lendario", valor: 1.30 },
    { nome: "Maneki-Neko", categoria: "Lendario", valor: 1.20 },
    { nome: "Cérbero", categoria: "Lendario", valor: 1.90 },
    { nome: "Pedra Maligna", categoria: "Raro", valor: 1.50 },
    { nome: "Ganso R", categoria: "Raro", valor: 0.99 },
    { nome: "Axolote", categoria: "Lendario", valor: 3.30 },
    { nome: "Dragão Dourado", categoria: "Lendario", valor: 1.10 },
    { nome: "Cobra", categoria: "Lendario", valor: 1.00 },
    { nome: "Joaninha Dourada", categoria: "Lendario", valor: 1.50 },
    { nome: "Leão Guardião", categoria: "Lendario", valor: 1.40 },
    { nome: "Cão Robô", categoria: "Lendario", valor: 1.10 },
    { nome: "Macaco de Negócios", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Corvo Espantalho", categoria: "Lendario", valor: 1.00 },
    { nome: "Macaco de Brinquedo", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Pavão", categoria: "Lendario", valor: 0.90 },
    { nome: "Gato Múmia Dourada de Halloween", categoria: "Lendario", valor: 1.00 },
    { nome: "Libélula", categoria: "Lendario", valor: 0.99 },
    { nome: "Zebra Flamingo", categoria: "Raro", valor: 0.99 },
    { nome: "Porco", categoria: "Raro", valor: 11.50 },
    { nome: "Grifo Dourado", categoria: "Lendario", valor: 0.99 },
    { nome: "Coruja Pesadelo", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Chickatrice Maligna", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo Dourado", categoria: "Lendario", valor: 0.99 },
    { nome: "Pintinho", categoria: "Comum", valor: 0.99 },
    { nome: "Spinel NP", categoria: "Raro", valor: 0.99 },
    { nome: "Chow-Chow Preto", categoria: "Lendario", valor: 1.50 },
    { nome: "Dragão", categoria: "Lendario", valor: 0.99 },
    { nome: "Grifo", categoria: "Lendario", valor: 0.99 },
    { nome: "Kitsune", categoria: "Lendario", valor: 1.00 },
    { nome: "Perdiz", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Pônei Bonito", categoria: "Ultra-Raro", valor: 3.99 },
    { nome: "Ovo do Oceano", categoria: "Lendario", valor: 0.99 },
    { nome: "Urso Lunar", categoria: "Lendario", valor: 0.99 },
    { nome: "Galinha", categoria: "Incomum", valor: 3.99 },
    { nome: "Lobo", categoria: "Incomum", valor: 2.50 },
    { nome: "Formiga MFR", categoria: "Incomum", valor: 3.50 },
    { nome: "Formiga N", categoria: "Incomum", valor: 0.90 },
    { nome: "Lobo NR", categoria: "Incomum", valor: 4.50 },
    { nome: "Ovo de Mascote", categoria: "Comum", valor: 0.99 },
    { nome: "Ovo Rachado", categoria: "Comum", valor: 0.99 },
    { nome: "Ovo Azul", categoria: "Incomum", valor: 0.99 },
    { nome: "Ovo Rosa", categoria: "Incomum", valor: 0.99 },
    { nome: "Ovo da Fazenda", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo da Selva", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Safari", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Fóssil", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Oceânico", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Mítico", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo de Natal", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Dourado", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo de Diamante", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo da Floresta", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo do Japão", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo do Sudeste Asiático", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Urbano", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo do Deserto", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo do Jardim", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Real do Deserto", categoria: "Lendario", valor: 0.99 },
    { nome: "Ovo Real da Lua", categoria: "Lendario", valor: 0.99 },
    { nome: "Ovo Real Asteca", categoria: "Lendario", valor: 0.99 },
    { nome: "Ovo do Tolinho", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo Estrela", categoria: "Raro", valor: 0.99 },
    { nome: "Ovo do Minion do Zodíaco", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo da Páscoa 2020", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo Aposentado", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo do Perigo", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo do Natal Futuro", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Ovo da Lua", categoria: "Ultra-Raro", valor: 0.99 },
    { nome: "Baleia Espacial", categoria: "Lendario", valor: 0.99 },
    { nome: "Leviatã", categoria: "Lendario", valor: 3.50 },
    { nome: "Pintinho do Minion do Zodíaco", categoria: "Lendario", valor: 0.99 },
    { nome: "Dragão de Diamante", categoria: "Lendario", valor: 0.99 },
    { nome: "Unicórnio de Diamante", categoria: "Lendario", valor: 3.00 },
    { nome: "Rena Ártica", categoria: "Lendario", valor: 78.00 },
    { nome: "Grifo de Diamante", categoria: "Lendario", valor: 0.99 },
    { nome: "Macaco Ninja", categoria: "Lendario", valor: 3.50 },
    { nome: "Skele-Rex", categoria: "Lendario", valor: 3.50 },
    { nome: "Búfalo Zumbi", categoria: "Lendario", valor: 8.50 },
    { nome: "Grifo Dourado", categoria: "Lendario", valor: 0.99 },
    { nome: "Leão Guardião", categoria: "Lendario", valor: 0.99 },
    { nome: "Boi Metálico", categoria: "Lendario", valor: 0.99 },
    { nome: "Dodô", categoria: "Lendario", valor: 3.00 },
    { nome: "T-Rex", categoria: "Lendario", valor: 3.00 },
    { nome: "Dragão de Lava", categoria: "Lendario", valor: 7.99 },
    { nome: "Dragão Mariposa de Gelo", categoria: "Lendario", valor: 1.10 },
    { nome: "Tigre Alado", categoria: "Lendario", valor: 15.00 },
    { nome: "Dragão Naga", categoria: "Lendario", valor: 0.99 },
    { nome: "Orca", categoria: "Lendario", valor: 0.66 },
    { nome: "Espinossauro", categoria: "Lendario", valor: 0.99 },
    { nome: "Dragão Vampiro", categoria: "Lendario", valor: 11.00 },
    { nome: "Dragão Sombrio", categoria: "Lendario", valor: 9.00 },
    { nome: "Hidra de Jekyll", categoria: "Lendario", valor: 19.00 },
    { nome: "Dragão da Meia-Noite", categoria: "Lendario", valor: 7.00 },
    { nome: "Dragão Arco-Íris", categoria: "Lendario", valor: 3.50 },
    { nome: "Falcão de Fogo Selvagem", categoria: "Lendario", valor: 0.99 },
    { nome: "Raposa Flamejante", categoria: "Lendario", valor: 71.00 },
    { nome: "Rinoceronte Vulcânico", categoria: "Lendario", valor: 1.70 },
    { nome: "Dragão do Crepúsculo Ártico", categoria: "Lendario", valor: 9.00 },
    { nome: "Fênix de Gelo",           categoria: "Lendario", valor: 7.00 },
    { nome: "Unicórnio de Gelo",       categoria: "Lendario", valor: 21.00 },
    { nome: "Cervo Celestial",         categoria: "Lendario", valor: 10.00 },
    { nome: "Dragão Dançante",         categoria: "Lendario", valor: 6.50 },
    { nome: "Lobo de Lava",            categoria: "Lendario", valor: 0.99 },
    { nome: "Kaijunior Abrasador",     categoria: "Lendario", valor: 3.50 },
    { nome: "Kaijunior Tóxico",        categoria: "Lendario", valor: 0.99 },
    { nome: "Kaijunior Primal",        categoria: "Lendario", valor: 0.99 },
    { nome: "Kaijunior",               categoria: "Lendario", valor: 0.50 },
    { nome: "Dragão Sombrio",          categoria: "Lendario", valor: 8.99 },
    { nome: "Cobra",                   categoria: "Lendario", valor: 1.25 },
    { nome: "Rato",                    categoria: "Lendario", valor: 0.99 },
    { nome: "Snow",                    categoria: "Lendario", valor: 1.79 },
    { nome: "Doguinho R",              categoria: "Lendario", valor: 1.65 },
    { nome: "Tucano",                  categoria: "Lendario", valor: 0.89 },
    { nome: "Rinoceronte",             categoria: "Lendario", valor: 2.99 },
    { nome: "Snowman",                 categoria: "Lendario", valor: 0.99 },
    { nome: "Pantera",                 categoria: "Lendario", valor: 1.49 },
    { nome: "Rainbow Dragon",          categoria: "Lendario", valor: 2.49 },
    { nome: "Robo Dog",                categoria: "Lendario", valor: 0.99 },
    { nome: "Borboleta",               categoria: "Lendario", valor: 0.89 },
    { nome: "Corvo Espantalho",        categoria: "Lendario", valor: 0.99 },
    { nome: "Pônei",                   categoria: "Lendario", valor: 0.99 },
    { nome: "Dinossauro NP",           categoria: "Lendario", valor: 0.99 },
    { nome: "Pinguim de Morango",      categoria: "Lendario", valor: 14.99 },
    { nome: "Lula Montável",           categoria: "Lendario", valor: 1.69 },
    { nome: "Calf",                    categoria: "Lendario", valor: 11.89 },
    { nome: "King Bee NR",             categoria: "Lendario", valor: 6.99 },
    { nome: "Urso Preto",              categoria: "Lendario", valor: 0.79 },
    { nome: "Queen Bee FR",            categoria: "Lendario", valor: 3.89 },
    { nome: "Pequenatalino",           categoria: "Lendario", valor: 5.99 },
    { nome: "Nessie",                  categoria: "Lendario", valor: 9.89 },
    { nome: "Princesa Macaco",         categoria: "Lendario", valor: 1.76 },
    { nome: "Coruja Pêssego",          categoria: "Lendario", valor: 7.50 },
    { nome: "Crocodilo",               categoria: "Ultra",    valor: 20.99 },
    { nome: "Elefante",                categoria: "Raro",     valor: 28.99 },
    { nome: "Ganso",                   categoria: "Raro",     valor: 28.79 },
    { nome: "Cabbit",                  categoria: "Lendario", valor: 33.89 },
    { nome: "Kanga NFR",               categoria: "Lendario", valor: 64.89 },
    { nome: "Suricata",                categoria: "Ultra",    valor: 9.99 },
    { nome: "Lince",                   categoria: "Raro",     valor: 3.99 },
    { nome: "Bat Morango FR",          categoria: "Lendario", valor: 43.99 },
    { nome: "Kanga R",                 categoria: "Lendario", valor: 29.89 },
    { nome: "Kanga FR",                categoria: "Lendario", valor: 29.89 },
    { nome: "Kanga NFR",               categoria: "Lendario", valor: 59.89 },
    { nome: "Ganso",                   categoria: "Raro",     valor: 26.89 },
    { nome: "Lebre",                   categoria: "Ultra",    valor: 0.90 },
    { nome: "Veículo de Estrela",      categoria: "Ultra",    valor: 34.99 },
    { nome: "Vaca FR",                 categoria: "Raro",     valor: 43.89 },
    { nome: "Arctic Fox NR",           categoria: "Ultra",    valor: 32.89 },
    { nome: "Bat Fada FR",             categoria: "Lendario", valor: 19.99 },
    { nome: "Rena Ártica FR",          categoria: "Lendario", valor: 72.89 },
    { nome: "Lara Nessie",             categoria: "Lendario", valor: 9.99 },
    { nome: "Pastor Alemão R",         categoria: "Ultra",    valor: 4.50 },
    { nome: "Pastor Alemão",           categoria: "Ultra",    valor: 3.99 },
    { nome: "Suricata R",              categoria: "Ultra",    valor: 9.99 },
    { nome: "Quokka NR",               categoria: "Raro",     valor: 4.59 },
    { nome: "Mecha Coelho", categoria: "Lendario", valor: 0.50 },
    { nome: "Mermicórnio", categoria: "Lendario", valor: 15.50 },
    { nome: "Quetzalcoatl", categoria: "Lendario", valor: 0.50 },
    { nome: "Onça", categoria: "Lendario", valor: 0.50 },
    { nome: "Ehecatl", categoria: "Lendario", valor: 0.50 },
    { nome: "Dragão Cupido", categoria: "Lendario", valor: 11.50 },
    { nome: "Haetae", categoria: "Lendario", valor: 51.00 },
    { nome: "Cobra Dourada", categoria: "Lendario", valor: 0.50 },
    { nome: "Cobra Prisma", categoria: "Lendario", valor: 0.50 },
    { nome: "Cobra Florida", categoria: "Lendario", valor: 0.50 },
    { nome: "Cobra Nebulosa", categoria: "Lendario", valor: 0.50 },
    { nome: "Tartaruga Chifruda", categoria: "Lendario", valor: 45.00 },
    { nome: "Dragonster", categoria: "Lendario", valor: 0.50 },
    { nome: "Dragão Morcego de Morango com Shortcake", categoria: "Lendario", valor: 47.00 },
    { nome: "Dragão Morcego de Chocolate com Chips", categoria: "Lendario", valor: 43.00 },
    { nome: "Espírito Sakura", categoria: "Lendario", valor: 8.00 },
    { nome: "Bakeneko", categoria: "Lendario", valor: 0.50 },
    { nome: "Corvo Kage", categoria: "Lendario", valor: 0.50 },
    { nome: "Mariposa Mirai", categoria: "Lendario", valor: 0.50 },
    { nome: "Criptídeo", categoria: "Lendario", valor: 57.00 },
    { nome: "Slimingo", categoria: "Lendario", valor: 0.50 },
    { nome: "Corredor de Lava", categoria: "Lendario", valor: 0.50 },
    { nome: "Dragão Fantasma", categoria: "Lendario", valor: 6.50 },
    { nome: "Urso Remendado", categoria: "Lendario", valor: 0.50 },
    { nome: "Morcego Esquelético", categoria: "Lendario", valor: 0.50 },
    { nome: "O Cão Negro", categoria: "Lendario", valor: 0.50 },
    { nome: "Aranha Arrepiante", categoria: "Lendario", valor: 0.50 },
    { nome: "Tinta para Pet Brilhante Marfim", categoria: "Lendario", valor: 0.50 },
    { nome: "Luz das Brasas", categoria: "Lendario", valor: 6.00 },
    { nome: "Abelha", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pinguim", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Panda Vermelho", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Shiba Inu", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Preguiça", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Estrela-do-Mar", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Tucano", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coala", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Sapo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Joaninha", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Ouriço", categoria: "Ultra-Raro", valor: 99.99 },
    { nome: "Elefante", categoria: "Ultra-Raro", valor: 30.00 },
    { nome: "Hiena", categoria: "Ultra-Raro", valor: 8.00 },
    { nome: "Meerkat", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Musaranho", categoria: "Ultra-Raro", valor: 10.00 },
    { nome: "Cachorro Azul", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Urso Marrom", categoria: "Ultra-Raro", valor: 8.50 },
    { nome: "Crocodilo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Rato Dourado", categoria: "Ultra-Raro", valor: 2.00 },
    { nome: "Javali", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Vaca", categoria: "Ultra-Raro", valor: 46.00 },
    { nome: "Pantera Negra", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pinguim Dourado", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Lhama", categoria: "Ultra-Raro", valor: 4.50 },
    { nome: "Rinoceronte", categoria: "Ultra-Raro", valor: 3.00 },
    { nome: "Coruja da Neve", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cisne", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peru", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Porco", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Gato Rosa", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Raposa Ártica", categoria: "Ultra-Raro", valor: 10.00 },
    { nome: "Joaninha Dourada", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Rena", categoria: "Ultra-Raro", valor: 1.60 },
    { nome: "Capivara", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Urso Polar", categoria: "Ultra-Raro", valor: 8.50 },
    { nome: "Macaco de Negócios", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pato", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coelho Fantasma", categoria: "Ultra-Raro", valor: 2.30 },
    { nome: "Pato Bobo", categoria: "Ultra-Raro", valor: 2.80 },
    { nome: "Macaco de Brinquedo", categoria: "Ultra-Raro", valor: 2.00 },
    { nome: "Lobo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Yeti", categoria: "Ultra-Raro", valor: 1.60 },
    { nome: "Lince", categoria: "Ultra-Raro", valor: 1.30 },
    { nome: "Cavalo", categoria: "Ultra-Raro", valor: 0.74 },
    { nome: "Cordeiro", categoria: "Ultra-Raro", valor: 3.00 },
    { nome: "Esquilo Vermelho", categoria: "Ultra-Raro", valor: 0.58 },
    { nome: "Papagaio-do-Mar", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Husky", categoria: "Ultra-Raro", valor: 4.00 },
    { nome: "Morsa", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Golem de Gelo", categoria: "Ultra-Raro", valor: 5.00 },
    { nome: "São Bernardo", categoria: "Ultra-Raro", valor: 0.62 },
    { nome: "Leopardo das Neves", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pomeranian", categoria: "Ultra-Raro", valor: 0.76 },
    { nome: "Cabra", categoria: "Ultra-Raro", valor: 13.50 },
    { nome: "Albatroz", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Foca de Fita", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cavalo Alado", categoria: "Ultra-Raro", valor: 3.00 },
    { nome: "Íbex", categoria: "Ultra-Raro", valor: 0.24 },
    { nome: "Spaniel de Água Irlandês", categoria: "Ultra-Raro", valor: 18.00 },
    { nome: "Pinguim Rei", categoria: "Ultra-Raro", valor: 0.60 },
    { nome: "Escaravelho", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Lula", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Camaleão", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Axolote", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Esquilo Voador", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Springer Spaniel", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Alce Irlandês", categoria: "Ultra-Raro", valor: 0.80 },
    { nome: "Arminho", categoria: "Ultra-Raro", valor: 0.16 },
    { nome: "Pônei Shetland", categoria: "Ultra-Raro", valor: 1.50 },
    { nome: "Pet Bola de Neve", categoria: "Ultra-Raro", valor: 2.00 },
    { nome: "Leão da Estepe", categoria: "Ultra-Raro", valor: 0.24 },
    { nome: "Rinoceronte Lanudo", categoria: "Ultra-Raro", valor: 1.00 },
    { nome: "Nessie", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Vaca das Terras Altas", categoria: "Ultra-Raro", valor: 0.62 },
    { nome: "Cão de Caça", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Mariposa da Geleira", categoria: "Ultra-Raro", valor: 8.00 },
    { nome: "Urso da Lua", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coelho Amami", categoria: "Ultra-Raro", valor: 0.40 },
    { nome: "Coelho da Lua", categoria: "Ultra-Raro", valor: 0.48 },
    { nome: "Coelho d'Água", categoria: "Ultra-Raro", valor: 0.68 },
    { nome: "Vaga-lume", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Gambá", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Gorila", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pombo Selvagem", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Lebre", categoria: "Ultra-Raro", valor: 9.00 },
    { nome: "Border Collie", categoria: "Ultra-Raro", valor: 19.50 },
    { nome: "Camundongo do Campo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Ganso", categoria: "Ultra-Raro", valor: 27.00 },
    { nome: "Tio de Natal", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Gato Pudim", categoria: "Ultra-Raro", valor: 0.60 },
    { nome: "Caracol Broto", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cachorro de Tronco de Yule", categoria: "Ultra-Raro", valor: 5.00 },
    { nome: "Patinho", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pônei de Exposição", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pônei Punk", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pônei Bonito", categoria: "Ultra-Raro", valor: 0.80 },
    { nome: "Pônei Majestoso", categoria: "Ultra-Raro", valor: 5.50 },
    { nome: "Unicórnio de Balão", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cachorro de Milho", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Touro de Rodeio", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Águia Careca", categoria: "Ultra-Raro", valor: 9.00 },
    { nome: "Tubarão-leopardo", categoria: "Ultra-Raro", valor: 3.00 },
    { nome: "Gaivota Ártica", categoria: "Ultra-Raro", valor: 0.12 },
    { nome: "Caranguejo-Eremita", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Marisco Feliz", categoria: "Ultra-Raro", valor: 6.50 },
    { nome: "Lagosta", categoria: "Ultra-Raro", valor: 0.26 },
    { nome: "Tartaruga da Ilha", categoria: "Ultra-Raro", valor: 9.00 },
    { nome: "Muitas Cavalas", categoria: "Ultra-Raro", valor: 8.50 },
    { nome: "Peixe Voador", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Filhote de Tubarão", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cachorro Quente", categoria: "Ultra-Raro", valor: 33.00 },
    { nome: "Piranha", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe-diabo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Hipopótamo", categoria: "Ultra-Raro", valor: 0.42 },
    { nome: "Sapo Flecha Venenosa", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Polvo de Anéis Azuis", categoria: "Ultra-Raro", valor: 0.80 },
    { nome: "Baiacu", categoria: "Ultra-Raro", valor: 1.30 },
    { nome: "Abutre-barbudo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cruzeiro Caranguejo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Frequentador de Praia", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Javali", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Avestruz", categoria: "Ultra-Raro", valor: 0.30 },
    { nome: "Cão Selvagem Africano", categoria: "Ultra-Raro", valor: 150.00 },
    { nome: "Fossa", categoria: "Ultra-Raro", valor: 0.12 },
    { nome: "Ave do Paraíso", categoria: "Ultra-Raro", valor: 0.36 },
    { nome: "Tamanduá-bandeira", categoria: "Ultra-Raro", valor: 6.00 },
    { nome: "Peixe-anjo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Casuar", categoria: "Ultra-Raro", valor: 0.24 },
    { nome: "Lêmure-de-cauda-anelada", categoria: "Ultra-Raro", valor: 9.00 },
    { nome: "Mosca-azul", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Barata", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Mangusto", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coruja-patagónica", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pombo-da-rocha", categoria: "Ultra-Raro", valor: 3.50 },
    { nome: "Leopardo Indiano", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Poodle de Brinquedo", categoria: "Ultra-Raro", valor: 0.30 },
    { nome: "Gato de Rua", categoria: "Ultra-Raro", valor: 7.50 },
    { nome: "Gaivota", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Milhafre-preto", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Bode", categoria: "Ultra-Raro", valor: 1.30 },
    { nome: "Gárgula", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Guaxinim", categoria: "Ultra-Raro", valor: 0.30 },
    { nome: "Chipmunk", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Zebra Cinzenta", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Zebra Flamejante", categoria: "Ultra-Raro", valor: 0.80 },
    { nome: "Leão Flamejante", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Alce de Magma", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Caracol de Magma", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Panda Vermelho Tostado", categoria: "Ultra-Raro", valor: 0.60 },
    { nome: "Kiwi", categoria: "Ultra-Raro", valor: 1.00 },
    { nome: "Pelicano", categoria: "Ultra-Raro", valor: 48.00 },
    { nome: "Enguia", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Fantasma", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Alce Morto-vivo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coruja Pesadelo", categoria: "Ultra-Raro", valor: 0.52 },
    { nome: "Cabra Fofa", categoria: "Ultra-Raro", valor: 0.16 },
    { nome: "Cão Fantasma", categoria: "Ultra-Raro", valor: 1.50 },
    { nome: "Cervo Terrível", categoria: "Ultra-Raro", valor: 1.20 },
    { nome: "Espantalho", categoria: "Ultra-Raro", valor: 0.20 },
    { nome: "Lodo", categoria: "Ultra-Raro", valor: 5.00 },
    { nome: "Lobisomem", categoria: "Ultra-Raro", valor: 10.00 },
    { nome: "Ganso Canadense", categoria: "Ultra-Raro", valor: 0.26 },
    { nome: "Cão Pastor Inglês", categoria: "Ultra-Raro", valor: 1.10 },
    { nome: "Lagarta", categoria: "Ultra-Raro", valor: 23.00 },
    { nome: "Vaca Chifruda", categoria: "Ultra-Raro", valor: 0.28 },
    { nome: "Galo", categoria: "Ultra-Raro", valor: 0.64 },
    { nome: "Alpaca", categoria: "Ultra-Raro", valor: 13.00 },
    { nome: "Mecha Meow", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Baleia Beluga", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Esquilo Quebra-Nozes", categoria: "Ultra-Raro", valor: 0.20 },
    { nome: "Viajante do Globo de Neve", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Lebre Ártica", categoria: "Ultra-Raro", valor: 0.12 },
    { nome: "Kitsune da Geleira", categoria: "Ultra-Raro", valor: 9.00 },
    { nome: "Foca Harpa", categoria: "Ultra-Raro", valor: 1.50 },
    { nome: "Macaco das Neves", categoria: "Ultra-Raro", valor: 2.00 },
    { nome: "Cachorro de Eggnog", categoria: "Ultra-Raro", valor: 0.46 },
    { nome: "Rato de Gengibre", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Acampador de Doces", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Kookaburra", categoria: "Ultra-Raro", valor: 6.50 },
    { nome: "Quokka", categoria: "Ultra-Raro", valor: 0.54 },
    { nome: "Diabo-da-Tasmânia", categoria: "Ultra-Raro", valor: 0.36 },
    { nome: "Água-viva", categoria: "Ultra-Raro", valor: 11.00 },
    { nome: "Criosphinx", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Abutre", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Corredor da Estrada", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Escorpião da Morte", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Diabo Espinhoso", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Órix", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cascavel", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Monstro de Gila", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe-da-areia", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coiote", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Tatu", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Marmota", categoria: "Ultra-Raro", valor: 8.00 },
    { nome: "Sapo-de-chifre-ornamentado", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Nautilus", categoria: "Ultra-Raro", valor: 0.84 },
    { nome: "Mahi Mahi", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Hamster", categoria: "Ultra-Raro", valor: 0.66 },
    { nome: "Pintinho de Algodão Doce", categoria: "Ultra-Raro", valor: 29.00 },
    { nome: "Ovinho", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Macaco-prego", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Fada Gaélica", categoria: "Ultra-Raro", valor: 1.90 },
    { nome: "Vaca do Trevo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Escorpião Subzero", categoria: "Ultra-Raro", valor: 0.24 },
    { nome: "Lobo Arrepiante", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Porco-espinho Gelado", categoria: "Ultra-Raro", valor: 0.56 },
    { nome: "Mamute Nevado", categoria: "Ultra-Raro", valor: 0.52 },
    { nome: "Pinguim Congelado", categoria: "Ultra-Raro", valor: 0.52 },
    { nome: "Urso de Mordida de Gelo", categoria: "Ultra-Raro", valor: 17.00 },
    { nome: "Gafanhoto de Árvore de Três Chifres", categoria: "Ultra-Raro", valor: 5.00 },
    { nome: "Cabbit", categoria: "Ultra-Raro", valor: 24.00 },
    { nome: "Gibão", categoria: "Ultra-Raro", valor: 0.08 },
    { nome: "Alce", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Rato-almiscarado", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Borboleta", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Camarão Imperador", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Assaltante de Kelp", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Lesma do Mar", categoria: "Ultra-Raro", valor: 8.50 },
    { nome: "Raia Manta", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Carriça", categoria: "Ultra-Raro", valor: 0.10 },
    { nome: "Perereca", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Gambá d'Água", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Chanekeh", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Tegu", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe Betta Laranja", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe Betta Rosa", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe Betta Azul", categoria: "Ultra-Raro", valor: 1.00 },
    { nome: "Pássaro do Amor", categoria: "Ultra-Raro", valor: 0.36 },
    { nome: "Rato Namorado", categoria: "Ultra-Raro", valor: 0.30 },
    { nome: "Chocalho de Bola com Pá", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Elefante-da-savana", categoria: "Ultra-Raro", valor: 15.00 },
    { nome: "Marlim Negro", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Falcão Peregrino", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Chita", categoria: "Ultra-Raro", valor: 3.00 },
    { nome: "Besouro da Singularidade", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cão Glormy", categoria: "Ultra-Raro", valor: 3.50 },
    { nome: "Leão Glormy", categoria: "Ultra-Raro", valor: 4.50 },
    { nome: "Beija-flor", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Mariposa do Luar", categoria: "Ultra-Raro", valor: 1.80 },
    { nome: "Ouriço do Mar", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe Drácula", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Anjo do Mar", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Peixe-leão", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Kraken", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Ratel", categoria: "Ultra-Raro", valor: 7.00 },
    { nome: "Frankenfelino", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Raposa Voadora Indiana", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Urso Espantalho", categoria: "Ultra-Raro", valor: 1.20 },
    { nome: "Panda Esqueleto do Mar", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Papagaio Drácula", categoria: "Ultra-Raro", valor: 0.30 },
    { nome: "Cegonha Marabu", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pintinho de Halloween", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coruja Túmulo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Onça Dourada", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Cereja no Topo", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Hipogrifo", categoria: "Ultra-Raro", valor: 3.30 },
    { nome: "Troll do Visco", categoria: "Ultra-Raro", valor: 0.76 },
    { nome: "Perdiz", categoria: "Ultra-Raro", valor: 0.46 },
    { nome: "Cão dos Pirenéus", categoria: "Ultra-Raro", valor: 0.90 },
    { nome: "Cervo do Inverno", categoria: "Ultra-Raro", valor: 1.30 },
    { nome: "Raposa da Aurora", categoria: "Ultra-Raro", valor: 7.50 },
    { nome: "Filhote de Mordida de Gelo", categoria: "Ultra-Raro", valor: 0.76 },
    { nome: "Hopbop", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Snorgle", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Pinheiro da Lua", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Zeópode", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Starmite", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Puptune", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Desviante Dimensional", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Planador Solar", categoria: "Ultra-Raro", valor: 1.20 },
    { nome: "Pinguins Dango", categoria: "Ultra-Raro", valor: 18.00 },
    { nome: "Shih Tzu", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Humbug", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Rolas", categoria: "Ultra-Raro", valor: 0.20 },
    { nome: "Sasquatch de Árvore", categoria: "Ultra-Raro", valor: 0.28 },
    { nome: "Maine Coon", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Espírito Natalino", categoria: "Ultra-Raro", valor: 0.66 },
    { nome: "Pug Bola de Neve", categoria: "Ultra-Raro", valor: 0.80 },
    { nome: "Gato 2D", categoria: "Ultra-Raro", valor: 13.00 },
    { nome: "Aberdeen Angus", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Troll do Visco Aconchegante", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Sra. Whiskerpips", categoria: "Ultra-Raro", valor: 0.48 },
    { nome: "Velho Rei Carvão", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Coelho Redemoinho", categoria: "Ultra-Raro", valor: 2.30 },
    { nome: "Fada da Neve Japonesa", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Samoyed", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Bezerro Angus", categoria: "Ultra-Raro", valor: 0.40 },
    { nome: "Ovo Básico", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Ovo de Cristal", categoria: "Ultra-Raro", valor: 0.50 },
    { nome: "Galinha", categoria: "Raro", valor: 0.50 },
    { nome: "Rato", categoria: "Raro", valor: 0.50 },
    { nome: "Morcego Albino", categoria: "Raro", valor: 0.64 },
    { nome: "Boi Lunar", categoria: "Raro", valor: 0.50 },
    { nome: "Boi-almiscarado", categoria: "Raro", valor: 0.80 },
    { nome: "Tordo", categoria: "Raro", valor: 0.50 },
    { nome: "Kelpie Australiano", categoria: "Raro", valor: 0.50 },
    { nome: "Emu", categoria: "Raro", valor: 0.50 },
    { nome: "Macaco", categoria: "Raro", valor: 0.50 },
    { nome: "Gato Gengibre", categoria: "Raro", valor: 0.50 },
    { nome: "Boi", categoria: "Raro", valor: 0.50 },
    { nome: "Morcego", categoria: "Raro", valor: 0.50 },
    { nome: "Deinonico", categoria: "Raro", valor: 0.50 },
    { nome: "Dingo", categoria: "Raro", valor: 0.50 },
    { nome: "Dente-de-sabre", categoria: "Raro", valor: 0.50 },
    { nome: "Bandicoot", categoria: "Raro", valor: 0.50 },
    { nome: "Dilofossauro", categoria: "Raro", valor: 0.50 },
    { nome: "Pterodáctilo", categoria: "Raro", valor: 0.50 },
    { nome: "Mamute Lanudo", categoria: "Raro", valor: 0.24 },
    { nome: "Gliptodonte", categoria: "Raro", valor: 0.32 },
    { nome: "Estegossauro", categoria: "Raro", valor: 0.50 },
    { nome: "Tricerátops", categoria: "Raro", valor: 0.50 },
    { nome: "Castor", categoria: "Raro", valor: 0.50 },
    { nome: "Coelhinho", categoria: "Raro", valor: 0.50 },
    { nome: "Preguiça Terrestre", categoria: "Raro", valor: 0.50 },
    { nome: "Coelho", categoria: "Raro", valor: 0.50 },
    { nome: "Puma das Neves", categoria: "Raro", valor: 0.50 },
    { nome: "Tigre-da-Tasmânia", categoria: "Raro", valor: 0.50 },
    { nome: "Labrador Chocolate", categoria: "Raro", valor: 0.50 },
    { nome: "Raposa Fennec", categoria: "Raro", valor: 0.50 },
    { nome: "Puma", categoria: "Raro", valor: 0.50 },
    { nome: "Gato das Neves", categoria: "Raro", valor: 0.50 },
    { nome: "Búfalo", categoria: "Raro", valor: 0.50 },
    { nome: "Gato", categoria: "Raro", valor: 0.50 },
    { nome: "Cachorro", categoria: "Raro", valor: 0.50 },
    { nome: "Lontra", categoria: "Raro", valor: 0.50 },
    { nome: "Sasquatch", categoria: "Raro", valor: 0.30 },
    { nome: "Cavalo Marinho", categoria: "Raro", valor: 0.50 },
    { nome: "Wyvern", categoria: "Raro", valor: 0.50 },
    { nome: "Wolpertinger", categoria: "Raro", valor: 0.50 },
    { nome: "Hidra", categoria: "Raro", valor: 0.50 },
    { nome: "Marta", categoria: "Raro", valor: 0.50 },
    { nome: "Falcão", categoria: "Raro", valor: 0.50 },
    { nome: "Sapo-boi", categoria: "Raro", valor: 0.50 },
    { nome: "Salamandra", categoria: "Raro", valor: 0.50 },
    { nome: "Veado Fallow", categoria: "Raro", valor: 7.00 },
    { nome: "Cardeal Vermelho", categoria: "Raro", valor: 0.50 },
    { nome: "Raposa Vermelha", categoria: "Raro", valor: 0.50 },
    { nome: "Pica-pau", categoria: "Raro", valor: 0.50 },
    { nome: "Pavão", categoria: "Raro", valor: 1.70 },
    { nome: "Peixe-palhaço", categoria: "Raro", valor: 0.48 },
    { nome: "Arraia", categoria: "Raro", valor: 0.50 },
    { nome: "Tubarão", categoria: "Raro", valor: 0.50 },
    { nome: "Narval", categoria: "Raro", valor: 0.50 },
    { nome: "Polvo", categoria: "Raro", valor: 0.50 },
    { nome: "Golfinho", categoria: "Raro", valor: 0.50 },
    { nome: "Cavalo-marinho", categoria: "Raro", valor: 0.50 },
    { nome: "Caranguejo", categoria: "Raro", valor: 0.50 },
    { nome: "Burro", categoria: "Raro", valor: 0.50 },
    { nome: "Camelo", categoria: "Raro", valor: 0.50 },
    { nome: "Camundongo", categoria: "Raro", valor: 0.50 },
    { nome: "Zebra", categoria: "Raro", valor: 0.50 },
    { nome: "Corgi", categoria: "Raro", valor: 0.50 },
    { nome: "Poodle", categoria: "Raro", valor: 0.50 },
    { nome: "Periquito", categoria: "Raro", valor: 0.50 },
    { nome: "Chow-Chow Marrom", categoria: "Raro", valor: 0.74 },
    { nome: "Chow-Chow Chocolate", categoria: "Raro", valor: 1.50 },
    { nome: "Chow-Chow Preto", categoria: "Raro", valor: 0.50 },
    { nome: "Borboleta Amarela", categoria: "Raro", valor: 0.50 },
    { nome: "Borboleta Escarlate", categoria: "Raro", valor: 0.60 },
    { nome: "Borboleta Roxa", categoria: "Raro", valor: 9.00 },
    { nome: "Borboleta Laranja", categoria: "Raro", valor: 2.50 },
    { nome: "Borboleta Verde", categoria: "Raro", valor: 0.50 },
    { nome: "Faisão de Peito Marrom", categoria: "Raro", valor: 0.60 },
    { nome: "Faisão de Peito Verde", categoria: "Raro", valor: 1.50 },
    { nome: "Faisão de Peito Preto", categoria: "Raro", valor: 16.00 },
    { nome: "Texugo", categoria: "Raro", valor: 0.50 },
    { nome: "Spaniel do Palácio Real", categoria: "Raro", valor: 1.20 },
    { nome: "Corgi Real", categoria: "Raro", valor: 2.30 },
    { nome: "Dugongo", categoria: "Raro", valor: 0.50 },
    { nome: "Toupeira Sado", categoria: "Raro", valor: 0.50 },
    { nome: "Besouro Rinoceronte", categoria: "Raro", valor: 0.50 },
    { nome: "Tanuki", categoria: "Raro", valor: 0.20 },
    { nome: "Íbis", categoria: "Raro", valor: 0.50 },
    { nome: "Carpa Koi", categoria: "Raro", valor: 0.52 },
    { nome: "Gato-leopardo", categoria: "Raro", valor: 0.60 },
    { nome: "Grou-de-coroa-vermelha", categoria: "Raro", valor: 0.50 },
    { nome: "Caranguejo-aranha", categoria: "Raro", valor: 0.50 },
    { nome: "Caracol de Alçapão", categoria: "Raro", valor: 0.50 },
    { nome: "Lesma", categoria: "Raro", valor: 0.50 },
    { nome: "Basilisco", categoria: "Raro", valor: 0.50 },
    { nome: "Borhyaena Gigante", categoria: "Raro", valor: 0.50 },
    { nome: "Mosquito", categoria: "Raro", valor: 0.50 },
    { nome: "Óculos de Sol Estrela", categoria: "Raro", valor: 0.50 },
    { nome: "Filhote de Leão", categoria: "Raro", valor: 13.00 },
    { nome: "Montaria de Chita Gigante", categoria: "Raro", valor: 0.50 },
    { nome: "Carrinho de Compras", categoria: "Raro", valor: 0.50 },
    { nome: "Borboleta de Aniversário 202", categoria: "Raro", valor: 0.50 },
    { nome: "Cobra do Jardim", categoria: "Raro", valor: 0.20 },
    { nome: "Toupeira", categoria: "Raro", valor: 0.50 },
    { nome: "Gorgulho", categoria: "Raro", valor: 0.50 },
    { nome: "Gaio Azul", categoria: "Raro", valor: 0.50 },
    { nome: "Louva-a-deus", categoria: "Raro", valor: 0.50 },
    { nome: "Gambá", categoria: "Raro", valor: 0.50 },
    { nome: "Mariposa de Bordo Rosada", categoria: "Raro", valor: 0.50 },
    { nome: "Besouro Tartaruga Dourado", categoria: "Raro", valor: 0.30 },
    { nome: "Amigo Cogumelo", categoria: "Raro", valor: 0.50 },
    { nome: "Porquinho", categoria: "Raro", valor: 0.50 },
    { nome: "Cabritinho", categoria: "Raro", valor: 0.50 },
    { nome: "Bezerro", categoria: "Raro", valor: 0.40 },
    { nome: "Cão Pintado Africano", categoria: "Raro", valor: 0.50 },
    { nome: "Carneiro", categoria: "Raro", valor: 3.00 },
    { nome: "Capricórnio", categoria: "Raro", valor: 0.50 },
    { nome: "Chifre Dourado", categoria: "Raro", valor: 1.70 },
    { nome: "Pinguim Dourado", categoria: "Raro", valor: 0.50 },
    { nome: "Papagaio-do-Mar", categoria: "Raro", valor: 10.00 },
    { nome: "Arraia", categoria: "Raro", valor: 0.50 },
    { nome: "Baú do Tesouro", categoria: "Raro", valor: 0.50 },
    { nome: "Mahi Mahi", categoria: "Raro", valor: 0.50 },
    { nome: "Narval", categoria: "Raro", valor: 0.50 },
    { nome: "Anjo do Mar", categoria: "Raro", valor: 0.50 },
    { nome: "Dólar de Areia Branco", categoria: "Raro", valor: 2.00 },
    { nome: "Peixe-palhaço", categoria: "Raro", valor: 0.50 },
    { nome: "Água-viva", categoria: "Raro", valor: 0.50 },
    { nome: "Peixe-leão", categoria: "Raro", valor: 0.50 },
    { nome: "Kraken", categoria: "Raro", valor: 0.50 },
    { nome: "Nautilus", categoria: "Raro", valor: 0.50 },
    { nome: "Polvo", categoria: "Raro", valor: 0.50 },
    { nome: "Tubarão", categoria: "Raro", valor: 0.50 },
    { nome: "Chickatrice", categoria: "Raro", valor: 0.50 },
    { nome: "Lesma", categoria: "Raro", valor: 0.50 },
    { nome: "Morcego", categoria: "Raro", valor: 0.50 },
    { nome: "Espantalho", categoria: "Raro", valor: 0.20 },
    { nome: "Basilisco", categoria: "Raro", valor: 0.52 },
    { nome: "Cegonha Marabu", categoria: "Raro", valor: 0.50 },
    { nome: "Cão Esqueleto Branco", categoria: "Raro", valor: 0.48 },
    { nome: "Fantasma", categoria: "Raro", valor: 0.50 },
    { nome: "Raposa Voadora Indiana", categoria: "Raro", valor: 0.50 },
    { nome: "Lodo", categoria: "Raro", valor: 0.50 },
    { nome: "Lobo Zumbi", categoria: "Raro", valor: 0.80 },
    { nome: "Cavalo de Justa", categoria: "Raro", valor: 0.50 },
    { nome: "Árvore de Natal", categoria: "Raro", valor: 0.50 },
    { nome: "Ratatoskr", categoria: "Raro", valor: 0.50 },
    { nome: "Boneco de Neve", categoria: "Raro", valor: 0.20 },
    { nome: "Trono do Papai Noel", categoria: "Raro", valor: 0.50 },
    { nome: "Corça do Inverno", categoria: "Raro", valor: 0.50 },
    { nome: "Amigos Enfeites", categoria: "Raro", valor: 0.50 },
    { nome: "Lebre de Gengibre", categoria: "Raro", valor: 0.50 },
    { nome: "Troll do Visco Alegre", categoria: "Raro", valor: 0.76 },
    { nome: "Troll do Visco Travesso", categoria: "Raro", valor: 3.50 },
    { nome: "Pinguim de Hortelã", categoria: "Raro", valor: 42.50 },
    { nome: "Flor de Cerejeira", categoria: "Raro", valor: 0.50 },
    { nome: "Árvore de Cerejeira", categoria: "Raro", valor: 0.50 },
    { nome: "Ovo de Páscoa", categoria: "Raro", valor: 0.50 },
    { nome: "Cesta de Ovos", categoria: "Raro", valor: 0.50 },
    { nome: "Planador", categoria: "Raro", valor: 0.50 },
    { nome: "Ovinho Pontilhado", categoria: "Raro", valor: 0.50 },
    { nome: "Patinho Flower Power", categoria: "Raro", valor: 0.64 },
    { nome: "Kappakid", categoria: "Raro", valor: 0.50 },
    { nome: "Tripulante de Kelp", categoria: "Raro", valor: 0.50 },
    { nome: "Caçador de Kelp", categoria: "Raro", valor: 0.50 },
    { nome: "Capitão de Kelp", categoria: "Raro", valor: 1.90 },
    { nome: "Gato Siamês", categoria: "Raro", valor: 8.00 },
    { nome: "Buldogue Francês", categoria: "Raro", valor: 2.50 },
    { nome: "Panda Gigante", categoria: "Raro", valor: 72.00 },
    { nome: "Gato Munchkin", categoria: "Raro", valor: 5.00 },
    { nome: "Schnauzer Miniatura", categoria: "Raro", valor: 2.50 },
    { nome: "Aranha Saltadora", categoria: "Raro", valor: 0.50 },
    { nome: "Tarântula", categoria: "Raro", valor: 0.50 },
    { nome: "Viúva Negra", categoria: "Raro", valor: 1.70 },
    { nome: "Aie-aie", categoria: "Raro", valor: 0.50 },
    { nome: "Gato Fantasmagórico", categoria: "Raro", valor: 0.50 },
    { nome: "Pinguim de Chocolate", categoria: "Ultra-raro", valor: 0.50 },
    { nome: "Pinguim de Baunilha", categoria: "Raro", valor: 5.50 },
    { nome: "Pinguim de Morango", categoria: "Raro", valor: 18.00 },
    { nome: "Boneco de Neve", categoria: "Incomum", valor: 0.50 },
    { nome: "Poção Voar no Pet", categoria: "Incomum", valor: 0.50 },
    { nome: "Poção Montar no Pet", categoria: "Incomum", valor: 0.50 },
    { nome: "Dilofossauro", categoria: "Comum", valor: 0.50 },
    { nome: "Pterodáctilo", categoria: "Comum", valor: 0.50 },
    { nome: "Mamute Lanudo", categoria: "Comum", valor: 0.50 },
    { nome: "Estegossauro", categoria: "Comum", valor: 0.50 },
    { nome: "Tricerátops", categoria: "Comum", valor: 0.50 },
    { nome: "Borboleta Diamante", categoria: "Lendario", valor: 102.00 },
    { nome: "Borboleta Orquídea", categoria: "Lendario", valor: 90.00 },
    { nome: "Panda Gigante", categoria: "Lendario", valor: 72.00 },
    { nome: "Tartaruga", categoria: "Lendario", valor: 40.00 },
    { nome: "Rei Macaco", categoria: "Lendario", valor: 40.00 },
    { nome: "Macaco Albino", categoria: "Lendario", valor: 31.00 },
    { nome: "Raposa de Fruta do Dragão", categoria: "Lendario", valor: 71.00 },
    { nome: "Coruja de Abacaxi", categoria: "Lendario", valor: 27.00 },
    { nome: "Cavalo de Justa Morto-Vivo", categoria: "Lendario", valor: 21.00 },
    { nome: "Unicórnio de Gelo", categoria: "Lendario", valor: 21.00 },
    { nome: "Alce Papa", categoria: "Lendario", valor: 21.00 },
    { nome: "Pinguim de Morango", categoria: "Lendario", valor: 17.00 },
    { nome: "Hidra de Jekyll", categoria: "Lendario", valor: 19.00 },
    { nome: "Pinguins Dango", categoria: "Lendario", valor: 18.00 },
    { nome: "Urso Mordida de Gelo", categoria: "Lendario", valor: 17.00 },
    { nome: "Faisão de Peito Preto", categoria: "Lendario", valor: 16.00 },
    { nome: "Tigre Alado", categoria: "Lendario", valor: 15.00 },
    { nome: "Elefante da Savana", categoria: "Lendario", valor: 15.00 },
    { nome: "Filhote de Alce", categoria: "Lendario", valor: 13.80 },
    { nome: "Tió De Nadal", categoria: "Lendario", valor: 12.50 },
    { nome: "Troll do Visco Real", categoria: "Lendario", valor: 12.50 },
    { nome: "Gato 2D", categoria: "Lendario", valor: 13.00 },
    { nome: "Macaco-prego Fantasma Pirata", categoria: "Lendario", valor: 13.00 },
    { nome: "Filhote de Tubarão", categoria: "Lendario", valor: 12.00 },
    { nome: "Dragão Cupido", categoria: "Lendario", valor: 13.50 },
    { nome: "Coruja-Urso", categoria: "Lendario", valor: 12.00 },
    { nome: "Fúria Gelada", categoria: "Lendario", valor: 11.50 },
    { nome: "Dragão Vampiro", categoria: "Lendario", valor: 11.00 },
    { nome: "Mechapup", categoria: "Lendario", valor: 10.50 },
    { nome: "Caelum Cervi", categoria: "Lendario", valor: 10.00 },
    { nome: "Lobisomem", categoria: "Lendario", valor: 10.00 },
    { nome: "Axolote de Açúcar", categoria: "Lendario", valor: 9.50 },
    { nome: "Amazona Diamante", categoria: "Lendario", valor: 9.50 },
    { nome: "Gorila Imperador", categoria: "Lendario", valor: 9.00 },
    { nome: "Kitsune da Geleira", categoria: "Lendario", valor: 9.00 },
    { nome: "Dragão Sombrio", categoria: "Lendario", valor: 9.00 },
    { nome: "Dragão do Crepúsculo Ártico", categoria: "Lendario", valor: 9.00 },
    { nome: "Coruja de Maçã", categoria: "Lendario", valor: 7.70 },
    { nome: "Espírito Sakura", categoria: "Lendario", valor: 8.00 },
    { nome: "Coruja de Pêssego", categoria: "Lendario", valor: 8.70 },
    { nome: "Dragão de Lava", categoria: "Lendario", valor: 8.00 },
    { nome: "Dragão Fantasma", categoria: "Lendario", valor: 8.50 },
    { nome: "Escaravelho Dourado Gigante", categoria: "Lendario", valor: 8.00 },
    { nome: "Raposa da Aurora", categoria: "Lendario", valor: 7.50 },
    { nome: "Albatroz Diamante", categoria: "Lendario", valor: 8.00 },
    { nome: "Dragão da Meia-Noite", categoria: "Lendario", valor: 7.00 },
    { nome: "Veado Fallow", categoria: "Lendario", valor: 7.00 },
    { nome: "Hamster Diamante", categoria: "Lendario", valor: 5.50 },
    { nome: "Dragão Fantasma Branco de Halloween", categoria: "Lendario", valor: 7.50 },
    { nome: "Dragão Dançante", categoria: "Lendario", valor: 6.50 },
    { nome: "Fênix de Gelo", categoria: "Lendario", valor: 7.00 },
    { nome: "Luz das Brasas", categoria: "Lendario", valor: 6.00 },
    { nome: "Chow-Chow Dourado", categoria: "Lendario", valor: 6.00 },
    { nome: "Unicórnio", categoria: "Lendario", valor: 8.00 },
    { nome: "Pinguim de Baunilha", categoria: "Lendario", valor: 5.50 },
    { nome: "Pônei Majestoso", categoria: "Lendario", valor: 5.50 },
    { nome: "Joaninha Diamante", categoria: "Lendario", valor: 5.00 },
    { nome: "Golem de Gelo", categoria: "Lendario", valor: 5.00 },
    { nome: "Dragão Lavanda", categoria: "Lendario", valor: 5.00 },
    { nome: "Cachorro de Tronco de Yule", categoria: "Lendario", valor: 5.00 },
    { nome: "Leão Glormy", categoria: "Lendario", valor: 4.50 },
    { nome: "Pinguim Rei Diamante", categoria: "Lendario", valor: 4.50 },
    { nome: "Lebre de Doce", categoria: "Lendario", valor: 4.50 },
    { nome: "Gorila Albino", categoria: "Lendario", valor: 4.00 },
    { nome: "Beija-flor Diamante", categoria: "Lendario", valor: 4.00 },
    { nome: "Borboleta Verde", categoria: "Lendario", valor: 4.00 },
    { nome: "Pinguim Dourado", categoria: "Lendario", valor: 3.80 },
    { nome: "Abelha Rainha", categoria: "Lendario", valor: 3.80 },
    { nome: "Troll do Visco Travesso", categoria: "Lendario", valor: 3.50 },
    { nome: "Cão Glormy", categoria: "Lendario", valor: 3.50 },
    { nome: "Gorila Astronauta", categoria: "Lendario", valor: 3.50 },
    { nome: "Leviatã", categoria: "Lendario", valor: 3.50 },
    { nome: "Macaco Ninja", categoria: "Lendario", valor: 3.50 },
    { nome: "Gibão Herói", categoria: "Lendario", valor: 3.50 },
    { nome: "Kaijunior Abrasador", categoria: "Lendario", valor: 3.50 },
    { nome: "Dragão Arco-Íris", categoria: "Lendario", valor: 3.50 },
    { nome: "Capricórnio", categoria: "Lendario", valor: 3.50 },
    { nome: "Skele-Rex", categoria: "Lendario", valor: 3.50 },
    { nome: "Fênix", categoria: "Lendario", valor: 3.50 },
    { nome: "Axolote", categoria: "Lendario", valor: 3.30 },
    { nome: "Vaga-lume", categoria: "Lendario", valor: 3.30 },
    { nome: "Morsa Dourada", categoria: "Lendario", valor: 3.30 },
    { nome: "Hipogrifo", categoria: "Lendario", valor: 3.30 },
    { nome: "Borboleta Prismática", categoria: "Lendario", valor: 3.00 },
    { nome: "Unicórnio Diamante", categoria: "Lendario", valor: 3.00 },
    { nome: "Cachorro de Milho", categoria: "Lendario", valor: 3.00 },
    { nome: "Borboleta Violeta", categoria: "Lendario", valor: 3.00 },
    { nome: "Cavalo de Justa", categoria: "Lendario", valor: 3.00 },
    { nome: "Amazona Branca", categoria: "Lendario", valor: 3.00 },
    { nome: "Vela Fofinha", categoria: "Lendario", valor: 3.00 },
    { nome: "Hamster Dourado", categoria: "Lendario", valor: 3.00 },
    { nome: "Chita", categoria: "Lendario", valor: 3.00 },
    { nome: "Dodô", categoria: "Lendario", valor: 3.00 },
    { nome: "Tubarão", categoria: "Lendario", valor: 3.00 },
    { nome: "T-Rex", categoria: "Lendario", valor: 3.00 },
    { nome: "Canguru Arbóreo", categoria: "Lendario", valor: 3.00 },
    { nome: "Cavalo Alado", categoria: "Lendario", valor: 3.00 },
    { nome: "Rato Dourado", categoria: "Lendario", valor: 2.00 },
    { nome: "Caranguejo-Eremita Pirata", categoria: "Lendario", valor: 1.90 },
    { nome: "Cérbero", categoria: "Lendario", valor: 1.90 },
    { nome: "Capitão de Kelp", categoria: "Lendario", valor: 1.90 },
    { nome: "Borboleta Luar", categoria: "Lendario", valor: 1.80 },
    { nome: "Polvo", categoria: "Lendario", valor: 1.80 },
    { nome: "Pavão", categoria: "Lendario", valor: 1.70 },
    { nome: "Dragão Naga", categoria: "Lendario", valor: 1.70 },
    { nome: "Rinoceronte Vulcânico", categoria: "Lendario", valor: 1.70 },
    { nome: "Pinguim Rei Dourado", categoria: "Lendario", valor: 1.70 },
    { nome: "Viúva Negra", categoria: "Lendario", valor: 1.70 },
    { nome: "Macaco-prego Real", categoria: "Lendario", valor: 1.70 },
    { nome: "Espinossauro", categoria: "Lendario", valor: 1.70 },
    { nome: "Chifre Dourado", categoria: "Lendario", valor: 1.70 },
    { nome: "Dragão Diamante", categoria: "Lendario", valor: 1.60 },
    { nome: "Amigo Cacto", categoria: "Lendario", valor: 1.60 },
    { nome: "Gárgula", categoria: "Lendario", valor: 1.60 },
    { nome: "Chow-Chow Preto", categoria: "Lendario", valor: 1.50 },
    { nome: "Chow-Chow Chocolate", categoria: "Lendario", valor: 1.50 },
    { nome: "Faisão de Peito Verde", categoria: "Lendario", valor: 1.50 },
    { nome: "Lobo de Lava", categoria: "Lendario", valor: 1.50 },
    { nome: "Lula", categoria: "Lendario", valor: 1.50 },
    { nome: "Camaleão", categoria: "Lendario", valor: 1.50 },
    { nome: "Pônei Shetland Marrom Claro", categoria: "Lendario", valor: 1.50 },
    { nome: "Joaninha Dourada", categoria: "Lendario", valor: 1.50 },
    { nome: "Abelha Rei", categoria: "Lendario", valor: 1.50 },
    { nome: "Patinho do Amanhecer", categoria: "Lendario", valor: 1.50 },
    { nome: "Albatroz Dourado", categoria: "Lendario", valor: 1.50 },
    { nome: "Dimorfodonte", categoria: "Lendario", valor: 1.50 },
    { nome: "Unicórnio Dourado", categoria: "Lendario", valor: 1.50 },
    { nome: "Criosphinx", categoria: "Lendario", valor: 1.50 },
    { nome: "Coruja da Neve", categoria: "Lendario", valor: 1.50 },
    { nome: "Leão Guardião", categoria: "Lendario", valor: 1.40 },
    { nome: "Grifo Diamante", categoria: "Lendario", valor: 1.40 },
    { nome: "Cobra Dourada", categoria: "Lendario", valor: 1.40 },
    { nome: "Beija-flor Dourado", categoria: "Lendario", valor: 1.40 },
    { nome: "Gibão Influenciador", categoria: "Lendario", valor: 1.40 },
    { nome: "Camarão Inestimável", categoria: "Lendario", valor: 1.40 },
    { nome: "Falcão", categoria: "Lendario", valor: 1.40 },
    { nome: "Alicorne", categoria: "Lendario", valor: 1.40 },
    { nome: "Amigo Cogumelo", categoria: "Lendario", valor: 1.40 },
    { nome: "Macaco-prego Princesa", categoria: "Lendario", valor: 1.30 },
    { nome: "Cervo do Inverno", categoria: "Lendario", valor: 1.30 },
    { nome: "Cubo de Bagas Geladas", categoria: "Lendario", valor: 1.30 },
    { nome: "Quimera", categoria: "Lendario", valor: 1.30 },
    { nome: "Bode", categoria: "Lendario", valor: 1.30 },
    { nome: "Fleur De Gelo", categoria: "Lendario", valor: 1.30 },
    { nome: "Baku", categoria: "Lendario", valor: 1.30 },
    { nome: "Dragão Antigo", categoria: "Lendario", valor: 1.30 },
    { nome: "Urso Espantalho", categoria: "Lendario", valor: 1.20 },
    { nome: "Cervo Terrível", categoria: "Lendario", valor: 1.20 },
    { nome: "Maneki-Neko", categoria: "Lendario", valor: 1.20 },
    { nome: "Planador Solar", categoria: "Lendario", valor: 1.20 },
    { nome: "Cão Robô", categoria: "Lendario", valor: 1.10 },
    { nome: "Dragão Mariposa de Gelo", categoria: "Lendario", valor: 1.10 },
    { nome: "Dragão Dourado", categoria: "Lendario", valor: 1.10 },
    { nome: "Ovinho Listrado", categoria: "Lendario", valor: 1.00 },
    { nome: "Corvo Espantalho", categoria: "Lendario", valor: 1.00 },
    { nome: "Super Saru", categoria: "Lendario", valor: 1.00 },
    { nome: "Peixe Betta Azul", categoria: "Lendario", valor: 1.00 },
    { nome: "Cobra", categoria: "Lendario", valor: 1.00 },
    { nome: "Gato Múmia Dourada de Halloween", categoria: "Lendario", valor: 1.00 },
    { nome: "Kitsune", categoria: "Lendario", valor: 1.00 },
    { nome: "Gato Morcego", categoria: "Lendario", valor: 1.00 },
    { nome: "Garra Gelada", categoria: "Lendario", valor: 1.00 },
    { nome: "Mahi Mahi Diamante", categoria: "Lendario", valor: 1.00 },
    { nome: "Espírito Natalino", categoria: "Lendario", valor: 0.66 },
    { nome: "Tigre Dourado Lunar", categoria: "Lendario", valor: 0.50 },
    { nome: "Boi Metálico", categoria: "Lendario", valor: 0.40 },
    { nome: "Pintinho do Minion do Zodíaco", categoria: "Lendario", valor: 0.36 },
    { nome: "Papagaio Drácula", categoria: "Lendario", valor: 0.30 },
    { nome: "Besouro Tartaruga Dourado", categoria: "Lendario", valor: 0.30 },
    { nome: "Vaca", categoria: "Lendario", valor: 46.00 },
    { nome: "Porco", categoria: "Lendario", valor: 11.50 },
    { nome: "Musaranho", categoria: "Lendario", valor: 10.00 },
    { nome: "Ganso", categoria: "Lendario", valor: 27.00 },
    { nome: "Border Collie", categoria: "Lendario", valor: 19.50 },
    { nome: "Lêmure-de-cauda-anelada", categoria: "Lendario", valor: 9.00 },
    { nome: "Urso Marrom", categoria: "Lendario", valor: 8.50 },
    { nome: "Urso Polar", categoria: "Lendario", valor: 8.50 },
    { nome: "Lebre", categoria: "Lendario", valor: 9.00 },
    { nome: "Tamanduá-bandeira", categoria: "Lendario", valor: 6.00 },
    { nome: "Husky", categoria: "Lendario", valor: 4.00 },
    { nome: "Mula", categoria: "Lendario", valor: 4.50 },
    { nome: "Gato Munchkin", categoria: "Lendario", valor: 5.00 },
    { nome: "Cisne", categoria: "Lendario", valor: 3.50 },
    { nome: "Tubarão-leopardo", categoria: "Lendario", valor: 3.00 },
    { nome: "Rinoceronte", categoria: "Lendario", valor: 3.00 },
    { nome: "Rena", categoria: "Lendario", valor: 1.60 },
    { nome: "Pedra Maligna", categoria: "Lendario", valor: 1.50 },
    { nome: "Buldogue Francês", categoria: "Lendario", valor: 2.50 },
    { nome: "Cão Fantasma", categoria: "Lendario", valor: 1.50 },
    { nome: "Lince", categoria: "Lendario", valor: 1.30 },
    { nome: "Cão Pastor Inglês", categoria: "Lendario", valor: 1.10 },
    { nome: "Kiwi", categoria: "Lendario", valor: 1.00 },
    { nome: "Patinho Feliz", categoria: "Lendario", valor: 1.00 },
    { nome: "Alce Irlandês", categoria: "Lendario", valor: 0.80 },
    { nome: "Boi-almiscarado", categoria: "Lendario", valor: 0.80 },
    { nome: "Caranguejo-Eremita do Castelo", categoria: "Lendario", valor: 0.80 },
    { nome: "Zebra Flamejante", categoria: "Lendario", valor: 0.80 },
    { nome: "Cão dos Pirenéus", categoria: "Lendario", valor: 0.90 },
    { nome: "Gato-leopardo", categoria: "Lendario", valor: 0.60 },
    { nome: "Gato Pudim", categoria: "Lendario", valor: 0.60 },
    { nome: "Morsa de Verão", categoria: "Lendario", valor: 0.52 },
    { nome: "Carpa Koi", categoria: "Lendario", valor: 0.52 },
    { nome: "Lagartixa", categoria: "Lendario", valor: 0.50 },
    { nome: "Chipmunk", categoria: "Lendario", valor: 0.50 },
    { nome: "Társio", categoria: "Lendario", valor: 0.48 },
    { nome: "Coelho da Lua", categoria: "Lendario", valor: 0.48 },
    { nome: "Hipopótamo", categoria: "Lendario", valor: 0.42 },
    { nome: "Lobo Arrepiante", categoria: "Lendario", valor: 0.40 },
    { nome: "Bezerro", categoria: "Lendario", valor: 0.40 },
    { nome: "Mariposa do Luar", categoria: "Lendario", valor: 0.40 },
    { nome: "Diabo-da-Tasmânia", categoria: "Lendario", valor: 0.36 },
    { nome: "Ave do Paraíso", categoria: "Lendario", valor: 0.36 },
    { nome: "Pássaro do Amor", categoria: "Lendario", valor: 0.36 },
    { nome: "Peixe Dourado", categoria: "Lendario", valor: 0.34 },
    { nome: "Sasquatch", categoria: "Lendario", valor: 0.30 },
    { nome: "Rato Namorado", categoria: "Lendario", valor: 0.30 },
    { nome: "Poodle de Brinquedo", categoria: "Lendario", valor: 0.30 },
    { nome: "Avestruz", categoria: "Lendario", valor: 0.30 },
    { nome: "Sasquatch de Árvore", categoria: "Lendario", valor: 0.28 },
    { nome: "Vaca Chifruda", categoria: "Lendario", valor: 0.28 },
    { nome: "Cão Salsicha do Mal de Halloween", categoria: "Lendario", valor: 0.26 },
    { nome: "Escorpião Subzero", categoria: "Lendario", valor: 0.24 },
    { nome: "Casuar", categoria: "Lendario", valor: 0.24 },
    { nome: "Leão da Estepe", categoria: "Lendario", valor: 0.24 },
    { nome: "Íbex", categoria: "Lendario", valor: 0.24 },
    { nome: "Cobra Nebulosa", categoria: "Lendario", valor: 0.20 },
    { nome: "Cobra da Flor", categoria: "Lendario", valor: 0.20 },
    { nome: "Cobra Prisma", categoria: "Lendario", valor: 0.20 },
    { nome: "Peixe", categoria: "Lendario", valor: 0.20 },
    { nome: "Coelho Mecha R4BBIT", categoria: "Lendario", valor: 0.20 },
    { nome: "Esquilo Quebra-Nozes", categoria: "Lendario", valor: 0.20 },
    { nome: "Mamute Lanudo", categoria: "Lendario", valor: 0.24 },
    { nome: "Rolinhas", categoria: "Lendario", valor: 0.20 },
    { nome: "Carriça", categoria: "Lendario", valor: 0.10 },
    { nome: "Gibão", categoria: "Lendario", valor: 0.08 },
    { nome: "Cachorro Azul", categoria: "Lendario", valor: 24.00 },
    { nome: "Gato Rosa", categoria: "Lendario", valor: 9.50 },
    { nome: "Meerkat", categoria: "Lendario", valor: 10.50 },
    { nome: "Javali", categoria: "Lendario", valor: 3.50 },
    { nome: "Pantera Negra", categoria: "Lendario", valor: 2.50 },
    { nome: "Pato Bobo", categoria: "Lendario", valor: 2.80 },
    { nome: "Capivara", categoria: "Lendario", valor: 2.50 },
    { nome: "Pato", categoria: "Lendario", valor: 2.30 },
    { nome: "Foca Harpa", categoria: "Lendario", valor: 1.50 },
    { nome: "Lobo", categoria: "Lendario", valor: 0.70 },
    { nome: "Quokka", categoria: "Lendario", valor: 0.54 },
    { nome: "Cachorro de Eggnog", categoria: "Lendario", valor: 0.46 },
    { nome: "Gliptodonte", categoria: "Lendario", valor: 0.32 },
    { nome: "Coelho Amami", categoria: "Lendario", valor: 0.40 },
    { nome: "Guaxinim", categoria: "Lendario", valor: 0.30 },
    { nome: "Lagosta", categoria: "Lendario", valor: 0.26 },
    { nome: "Cão de Terapia", categoria: "Lendario", valor: 0.26 },
    { nome: "Dingo", categoria: "Lendario", valor: 0.50 },
    { nome: "Ganso Canadense", categoria: "Lendario", valor: 0.26 },
    { nome: "Borboleta de Elevação 2021", categoria: "Lendario", valor: 0.24 },
    { nome: "Borboleta de Elevação 2022", categoria: "Lendario", valor: 0.20 },
    { nome: "Tanuki", categoria: "Lendario", valor: 0.20 },
    { nome: "Leopardo das Neves", categoria: "Lendario", valor: 0.20 },
    { nome: "Espantalho", categoria: "Lendario", valor: 0.20 },
    { nome: "Boneco de Neve", categoria: "Lendario", valor: 0.20 },
    { nome: "Javali", categoria: "Lendario", valor: 0.16 },
    { nome: "Arminho", categoria: "Lendario", valor: 0.16 },
    { nome: "Cabra Fofa", categoria: "Lendario", valor: 0.16 },
    { nome: "Pedra", categoria: "Lendario", valor: 0.16 },
    { nome: "Chickatrice", categoria: "Lendario", valor: 0.50 },
    { nome: "Enguia", categoria: "Lendario", valor: 0.50 },
    { nome: "Borboleta de Aniversário 2024", categoria: "Lendario", valor: 0.50 },
    { nome: "Borboleta de Aniversário 2023", categoria: "Lendario", valor: 0.50 },
    { nome: "Velho Rei Carvão", categoria: "Lendario", valor: 0.50 },
    { nome: "Morcego", categoria: "Lendario", valor: 0.50 },
    { nome: "Fossa", categoria: "Lendario", valor: 0.12 },
    { nome: "Borboleta de Aniversário 2025", categoria: "Lendario", valor: 0.50 },
    { nome: "Troll do Visco", categoria: "Lendario", valor: 0.12 },
    { nome: "Gaivota Ártica", categoria: "Lendario", valor: 0.12 },
    { nome: "Lebre Ártica", categoria: "Lendario", valor: 0.12 },
    { nome: "Dálmata", categoria: "Lendario", valor: 87.00 },
    { nome: "Flamingo", categoria: "Lendario", valor: 35.00 },
    { nome: "Crocodilo", categoria: "Lendario", valor: 23.50 },
    { nome: "Leão", categoria: "Lendario", valor: 22.00 },
    { nome: "Raposa Ártica", categoria: "Lendario", valor: 10.00 },
    { nome: "Ornitorrinco", categoria: "Lendario", valor: 8.00 },
    { nome: "Cão Selvagem Africano", categoria: "Lendario", valor: 114.00 },
    { nome: "Pelicano", categoria: "Lendario", valor: 48.00 },
    { nome: "Pinguim de Hortelã", categoria: "Lendario", valor: 42.50 },
    { nome: "Mini Pig", categoria: "Lendario", valor: 33.50 },
    { nome: "Lagarta", categoria: "Lendario", valor: 23.00 },
    { nome: "Cabbit", categoria: "Lendario", valor: 24.00 },
    { nome: "Spaniel de Água Irlandês", categoria: "Lendario", valor: 18.00 },
    { nome: "Cabra", categoria: "Lendario", valor: 13.50 },
    { nome: "Filhote de Leão", categoria: "Lendario", valor: 13.00 },
    { nome: "Alpaca", categoria: "Lendario", valor: 13.00 },
    { nome: "Água-viva", categoria: "Lendario", valor: 11.00 },
    { nome: "Ovelha", categoria: "Lendario", valor: 11.00 },
    { nome: "Papagaio-do-Mar", categoria: "Lendario", valor: 10.00 },
    { nome: "Borboleta Roxa", categoria: "Lendario", valor: 9.00 },
    { nome: "Águia Careca", categoria: "Lendario", valor: 9.00 },
    { nome: "Tartaruga da Ilha", categoria: "Lendario", valor: 9.00 },
    { nome: "Búfalo Zumbi", categoria: "Lendario", valor: 8.50 },
    { nome: "Muitas Cavalas", categoria: "Lendario", valor: 8.50 },
    { nome: "Lesma do Mar", categoria: "Lendario", valor: 8.50 },
    { nome: "Gato Siamês", categoria: "Lendario", valor: 8.00 },
    { nome: "Mariposa da Geleira", categoria: "Lendario", valor: 8.00 },
    { nome: "Marmota", categoria: "Lendario", valor: 8.00 },
    { nome: "Cão de Natal Pudim", categoria: "Lendario", valor: 7.50 },
    { nome: "Gato de Rua", categoria: "Lendario", valor: 7.50 },
    { nome: "Ratel", categoria: "Lendario", valor: 7.00 },
    { nome: "Kookaburra", categoria: "Lendario", valor: 6.50 },
    { nome: "Marisco Feliz", categoria: "Lendario", valor: 6.50 },
    { nome: "Gafanhoto de Árvore de Três Chifres", categoria: "Lendario", valor: 5.00 },
    { nome: "Raposa Flamejante", categoria: "Lendario", valor: 5.00 },
    { nome: "Lodo", categoria: "Lendario", valor: 5.00 },
    { nome: "Lhama", categoria: "Lendario", valor: 4.50 },
    { nome: "Peru", categoria: "Lendario", valor: 4.50 },
    { nome: "Lobo de Gelo", categoria: "Lendario", valor: 4.00 },
    { nome: "Caranguejo-Eremita de Sorvete", categoria: "Lendario", valor: 3.50 },
    { nome: "Pombo Selvagem", categoria: "Lendario", valor: 3.50 },
    { nome: "Cordeiro", categoria: "Lendario", valor: 3.00 },
    { nome: "Carneiro", categoria: "Lendario", valor: 3.00 },
    { nome: "Borboleta Laranja", categoria: "Lendario", valor: 2.50 },
    { nome: "Schnauzer Miniatura", categoria: "Lendario", valor: 2.50 },
    { nome: "Corgi Real", categoria: "Lendario", valor: 2.30 },
    { nome: "Coelho Fantasma", categoria: "Lendario", valor: 2.30 },
    { nome: "Coelho Redemoinho", categoria: "Lendario", valor: 2.30 },
    { nome: "Dólar de Areia Branco", categoria: "Lendario", valor: 2.00 },
    { nome: "Dólar de Areia Vermelho", categoria: "Lendario", valor: 2.00 },
    { nome: "Pet Bola de Neve", categoria: "Lendario", valor: 2.00 },
    { nome: "Macaco de Brinquedo", categoria: "Lendario", valor: 2.00 },
    { nome: "Macaco das Neves", categoria: "Lendario", valor: 2.00 },
    { nome: "Chef Gorila", categoria: "Lendario", valor: 1.90 },
    { nome: "Fada Gaélica", categoria: "Lendario", valor: 1.90 },
    { nome: "Sr. Whiskerpips", categoria: "Lendario", valor: 1.80 },
    { nome: "Yeti", categoria: "Lendario", valor: 1.60 },
    { nome: "Baiacu", categoria: "Lendario", valor: 1.30 },
    { nome: "Macaco de Negócios", categoria: "Lendario", valor: 1.20 },
    { nome: "Spaniel do Palácio Real", categoria: "Lendario", valor: 1.20 },
    { nome: "Binturong", categoria: "Lendario", valor: 1.20 },
    { nome: "Rinoceronte Lanudo", categoria: "Lendario", valor: 1.00 },
    { nome: "Springer Spaniel Marrom", categoria: "Lendario", valor: 0.90 },
    { nome: "Springer Spaniel Preto", categoria: "Lendario", valor: 0.90 },
    { nome: "Nautilus", categoria: "Lendario", valor: 0.84 },
    { nome: "Panda", categoria: "Lendario", valor: 0.84 },
    { nome: "Escaravelho Azul Gigante", categoria: "Lendario", valor: 0.84 },
    { nome: "Lobo Zumbi", categoria: "Lendario", valor: 0.80 },
    { nome: "Pônei Bonito", categoria: "Lendario", valor: 0.80 },
    { nome: "Polvo de Anéis Azuis", categoria: "Lendario", valor: 0.80 },
    { nome: "Gorila de Karatê", categoria: "Lendario", valor: 0.76 },
    { nome: "Troll do Visco Alegre", categoria: "Lendario", valor: 0.76 },
    { nome: "Filhote de Mordida de Gelo", categoria: "Lendario", valor: 0.76 },
    { nome: "Pomeranian", categoria: "Lendario", valor: 0.76 },
    { nome: "Cavalo", categoria: "Lendario", valor: 0.74 },
    { nome: "Coruja Clementina", categoria: "Lendario", valor: 0.76 },
    { nome: "Chow-Chow Marrom", categoria: "Lendario", valor: 0.74 },
    { nome: "Amazona Verde", categoria: "Lendario", valor: 0.74 },
    { nome: "Gato Espantalho", categoria: "Lendario", valor: 0.72 },
    { nome: "Escaravelho Preto Gigante", categoria: "Lendario", valor: 0.72 },
    { nome: "Alce Mãe", categoria: "Lendario", valor: 0.70 },
    { nome: "Pug Bola de Neve", categoria: "Lendario", valor: 0.80 },
    { nome: "Coelho d'Água", categoria: "Lendario", valor: 0.68 },
    { nome: "Hamster", categoria: "Lendario", valor: 0.66 },
    { nome: "Orca", categoria: "Lendario", valor: 0.66 },
    { nome: "Patinho Flower Power", categoria: "Lendario", valor: 0.64 },
    { nome: "Galo", categoria: "Lendario", valor: 0.64 },
    { nome: "Coala", categoria: "Lendario", valor: 0.64 },
    { nome: "Morcego Albino", categoria: "Lendario", valor: 0.64 },
    { nome: "São Bernardo", categoria: "Lendario", valor: 0.62 },
    { nome: "Vaca das Terras Altas", categoria: "Lendario", valor: 0.62 },
    { nome: "Baleia Espacial", categoria: "Lendario", valor: 0.64 },
    { nome: "Sapo", categoria: "Lendario", valor: 0.60 },
    { nome: "Esquilo Vermelho", categoria: "Lendario", valor: 0.58 },
    { nome: "Pinguim de Chocolate", categoria: "Lendario", valor: 0.56 },
    { nome: "Porco-espinho Gelado", categoria: "Lendario", valor: 0.56 },
    { nome: "Cão Pastor Inglês", categoria: "Lendario", valor: 1.10 },
    { nome: "Gato Pudim", categoria: "Lendario", valor: 0.60 },
    { nome: "Caracol Broto", categoria: "Lendario", valor: 0.50 },
    { nome: "Cachorro de Tronco de Yule", categoria: "Lendario", valor: 5.00 },
    { nome: "Patinho", categoria: "Lendario", valor: 0.50 },
    { nome: "Pônei de Exposição", categoria: "Lendario", valor: 0.50 },
    { nome: "Pônei Punk", categoria: "Lendario", valor: 0.50 },
    { nome: "Cachorro de Milho", categoria: "Lendario", valor: 0.50 },
    { nome: "Touro de Rodeio", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe Voador", categoria: "Lendario", valor: 0.50 },
    { nome: "Piranha", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe-diabo", categoria: "Lendario", valor: 0.50 },
    { nome: "Sapo Flecha Venenosa", categoria: "Lendario", valor: 0.50 },
    { nome: "Abutre-barbudo", categoria: "Lendario", valor: 0.50 },
    { nome: "Cruzeiro Caranguejo", categoria: "Lendario", valor: 0.50 },
    { nome: "Frequentador de Praia", categoria: "Lendario", valor: 0.50 },
    { nome: "Javali", categoria: "Lendario", valor: 0.50 },
    { nome: "Mosca-azul", categoria: "Lendario", valor: 0.50 },
    { nome: "Barata", categoria: "Lendario", valor: 0.50 },
    { nome: "Mangusto", categoria: "Lendario", valor: 0.50 },
    { nome: "Coruja-patagónica", categoria: "Lendario", valor: 0.50 },
    { nome: "Leopardo Indiano", categoria: "Lendario", valor: 0.50 },
    { nome: "Gaivota", categoria: "Lendario", valor: 0.50 },
    { nome: "Milhafre-preto", categoria: "Lendario", valor: 0.50 },
    { nome: "Chipmunk", categoria: "Lendario", valor: 0.50 },
    { nome: "Zebra Cinzenta", categoria: "Lendario", valor: 0.50 },
    { nome: "Leão Flamejante", categoria: "Lendario", valor: 0.50 },
    { nome: "Alce de Magma", categoria: "Lendario", valor: 0.50 },
    { nome: "Caracol de Magma", categoria: "Lendario", valor: 0.50 },
    { nome: "Fantasma", categoria: "Lendario", valor: 0.50 },
    { nome: "Alce Morto-vivo", categoria: "Lendario", valor: 0.50 },
    { nome: "Mecha Meow", categoria: "Lendario", valor: 0.50 },
    { nome: "Baleia Beluga", categoria: "Lendario", valor: 0.50 },
    { nome: "Viajante do Globo de Neve", categoria: "Lendario", valor: 0.50 },
    { nome: "Rato de Gengibre", categoria: "Lendario", valor: 0.50 },
    { nome: "Acampador de Doces", categoria: "Lendario", valor: 0.50 },
    { nome: "Criosphinx", categoria: "Lendario", valor: 0.50 },
    { nome: "Abutre", categoria: "Lendario", valor: 0.50 },
    { nome: "Corredor da Estrada", categoria: "Lendario", valor: 0.50 },
    { nome: "Escorpião da Morte", categoria: "Lendario", valor: 0.50 },
    { nome: "Diabo Espinhoso", categoria: "Lendario", valor: 0.50 },
    { nome: "Órix", categoria: "Lendario", valor: 0.50 },
    { nome: "Cascavel", categoria: "Lendario", valor: 0.50 },
    { nome: "Monstro de Gila", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe-da-areia", categoria: "Lendario", valor: 0.50 },
    { nome: "Coiote", categoria: "Lendario", valor: 0.50 },
    { nome: "Tatu", categoria: "Lendario", valor: 0.50 },
    { nome: "Sapo-de-chifre-ornamentado", categoria: "Lendario", valor: 0.50 },
    { nome: "Mahi Mahi", categoria: "Lendario", valor: 0.50 },
    { nome: "Ovinho", categoria: "Lendario", valor: 0.50 },
    { nome: "Macaco-prego", categoria: "Lendario", valor: 0.50 },
    { nome: "Vaca do Trevo", categoria: "Lendario", valor: 0.50 },
    { nome: "Lobo Arrepiante", categoria: "Lendario", valor: 0.50 },
    { nome: "Alce", categoria: "Lendario", valor: 0.50 },
    { nome: "Rato-almiscarado", categoria: "Lendario", valor: 0.50 },
    { nome: "Borboleta", categoria: "Lendario", valor: 0.50 },
    { nome: "Camarão Imperador", categoria: "Lendario", valor: 0.50 },
    { nome: "Assaltante de Kelp", categoria: "Lendario", valor: 0.50 },
    { nome: "Raia Manta", categoria: "Lendario", valor: 0.50 },
    { nome: "Perereca", categoria: "Lendario", valor: 0.50 },
    { nome: "Gambá d'Água", categoria: "Lendario", valor: 0.50 },
    { nome: "Chanekeh", categoria: "Lendario", valor: 0.50 },
    { nome: "Tegu", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe Betta Laranja", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe Betta Rosa", categoria: "Lendario", valor: 0.50 },
    { nome: "Chocalho de Bola com Pá", categoria: "Lendario", valor: 0.50 },
    { nome: "Marlim Negro", categoria: "Lendario", valor: 0.50 },
    { nome: "Falcão Peregrino", categoria: "Lendario", valor: 0.50 },
    { nome: "Besouro da Singularidade", categoria: "Lendario", valor: 0.50 },
    { nome: "Beija-flor", categoria: "Lendario", valor: 0.50 },
    { nome: "Ouriço do Mar", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe Drácula", categoria: "Lendario", valor: 0.50 },
    { nome: "Anjo do Mar", categoria: "Lendario", valor: 0.50 },
    { nome: "Peixe-leão", categoria: "Lendario", valor: 0.50 },
    { nome: "Kraken", categoria: "Lendario", valor: 0.50 },
    { nome: "Frankenfelino", categoria: "Lendario", valor: 0.50 },
    { nome: "Raposa Voadora Indiana", categoria: "Lendario", valor: 0.50 },
    { nome: "Panda Esqueleto do Mar", categoria: "Lendario", valor: 0.50 },
    { nome: "Cegonha Marabu", categoria: "Lendario", valor: 0.50 },
    { nome: "Pintinho de Halloween", categoria: "Lendario", valor: 0.50 },
    { nome: "Coruja Túmulo", categoria: "Lendario", valor: 0.50 },
    { nome: "Onça Dourada", categoria: "Lendario", valor: 0.50 },
    { nome: "Cereja no Topo", categoria: "Lendario", valor: 0.50 },
    { nome: "Hopbop", categoria: "Lendario", valor: 0.50 },
    { nome: "Snorgle", categoria: "Lendario", valor: 0.50 },
    { nome: "Pinheiro da Lua", categoria: "Lendario", valor: 0.50 },
    { nome: "Zeópode", categoria: "Lendario", valor: 0.50 },
    { nome: "Starmite", categoria: "Lendario", valor: 0.50 },
    { nome: "Puptune", categoria: "Lendario", valor: 0.50 },
    { nome: "Desviante Dimensional", categoria: "Lendario", valor: 0.50 },
    { nome: "Shih Tzu", categoria: "Lendario", valor: 0.50 },
    { nome: "Humbug", categoria: "Lendario", valor: 0.50 },
    { nome: "Maine Coon", categoria: "Lendario", valor: 0.50 },
    { nome: "Fada da Neve Japonesa", categoria: "Lendario", valor: 0.50 },
    { nome: "Samoyed", categoria: "Lendario", valor: 0.50 },
    { nome: "Troll do Visco Aconchegante", categoria: "Lendario", valor: 0.50 },
    { nome: "Sra. Whiskerpips", categoria: "Lendario", valor: 0.48 },
    { nome: "Aberdeen Angus", categoria: "Lendario", valor: 0.50 },
    { nome: "Bezerro Angus", categoria: "Lendario", valor: 0.40 },
    { nome: "Borboleta Diamante", categoria: "Lendario", valor: 102.00 }
];
